name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: backend-dev

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./deligance
          file: ./deligance/Dockerfile
          push: false
          tags: nextjs-dev

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml up -d
          # Replace with your test commands
          docker-compose exec backend npm test  # Adjust based on your backend test setup
          docker-compose down
